
backend:
  name: git-gateway
  branch: master
media_library:
  name: cloudinary
  config:
    cloud_name: dta9vptzh
    api_key: 651661895481873
    multiple: true
public_folder: /image
publish_mode: editorial_workflow

collections:
  - name: product
    label: Products
    extension: json
    format: json
    files:
      - label: "Products"
        name: "products"
        file: "/public/content/content.json"
        fields:
          - {label: Title, name: title, widget: string}
          - label: Products
            name: products
            widget: list
            fields:
              - {name: name, label: Name, widget: "string"}
              - {name: id, label: Id, widget: "string"}
              - {name: description, label: Description, widget:"string"}
              - {label: "Price", name: "price", widget: "number"}
              - {label: "Publish Date", name: "date", widget: "datetime"}
              - label: "Currency"
                name: "currency"
                widget: "select"
                options: ["EUR","USD"]
              - label: "Category"
                name: "category"
                widget: "select"
                options: ["paarden","stallen","dekjes"]
              - name: image
                label: Image
                widget: 'image'
                valueField: "{{slug}}"


    # folder: "content/products"
    # create: true
    # extension: json
    # format: json
    # fields:
      # - {name: title, label: Title, widget: "string"}
      # - {name: sku, label: Sku, widget: "string"}
      # - {name: description, label: Description, widget:"string"}
      # - {label: "Price", name: "price", widget: "string", pattern: ['(?<=^| )\d+(\.\d+)?(?=$| )', "must be a number"]}
      # - {label: "Publish Date", name: "date", widget: "datetime"}
      # - label: "Category"
      #   name: "category"
      #   widget: "select"
      #   options: ["paarden","stallen","dekjes"]
      # - name: image
      #   label: Image
      #   widget: 'image'
      #   valueField: "{{slug}}"


